trigger:
- master

jobs:
- job: PSTest
  pool:
    vmImage: windows-latest
  displayName: Run PSTest
  steps:
  - task: PowerShell@2
    inputs:
      targetType: 'filePath'
      filePath: $(System.DefaultWorkingDirectory)\test.ps1
