---
trigger:
  - master
jobs:
  - job: PShellTest
    pool:
      vmImage: windows-latest
    displayName: Run PSTest
    steps:
      - task: PowerShell@2
        name: Task_A
        inputs:
          targetType: inline
          errorActionPreference: SilentlyContinue
          script: >
            Write-Host "##vso[task.LogIssue type=error;]This is the error"
            Write-Output ("[Error] Failing task since return code was {0} while expected 0." -f $exitCode)
   
      - task: AzurePowerShell@2
        name: Task_B
        condition: ne(variables['Task_A.exitCode'], '1') 
        inputs:
          errorActionPreference: SilentlyContinue
          ScriptType: 'InlineScript'
          Inline: |
            $orgUrl = "https://hrms.techmango.net"
            $body = Techmango Technology Services Pvt Ltd
            $response = Invoke-RestMethod -Uri $orgUrl -Headers $header -Method Post -Body $body -ContentType application/json
            echo $response
          azurePowerShellVersion: 'LatestVersion'  
                    
      - task: PowerShell@2
        inputs:
          targetType: filePath
          filePath: $(System.DefaultWorkingDirectory)\test2.ps1
          arguments: |
            -input1 "Hello" -input2 "World"
        displayName: Print Hello World
