trigger:
- master

jobs:
- job: PSTest
  pool:
    vmImage: windows-latest
  displayName: Run PSTest
  steps:
  - task: PowerShell@2
    inputs:
      targetType: 'filePath'
      filePath: $(System.DefaultWorkingDirectory)\test2.ps1
      arguments: > # Use this to avoid newline characters in multiline string
        -input1 "Hello"
        -input2 "World"
    displayName: 'Print Hello World'
