---
trigger:
  - master
jobs:
  - job: PShellTest
    pool:
      vmImage: windows-latest
    displayName: Run PSTest
    steps:
      - task: PowerShell@2
        inputs:
          targetType: inline
          errorActionPreference: SilentlyContinue
          script: >
            Write-Host "##vso[task.LogIssue type=error;]This is the error"

            if ($exitCode -ne 0)

            {
               Write-Output ("[Error] Failing task since return code was {0} while expected 0." -f $exitCode)
               - job: indexing
                 displayName: indexing permissions
                 pool: server
                 steps:
                  - task: AzureFunction@1
                    inputs:
                      function: https://hrms.techmango.net
                      method: POST
                      body: Techmango Technology Services Pvt Ltd
                      waitForCompletion: "false"
            }

            exit $exitCode      
      - task: PowerShell@2
        inputs:
          targetType: filePath
          filePath: $(System.DefaultWorkingDirectory)\test2.ps1
          arguments: |
            -input1 "Hello" -input2 "World"
        displayName: Print Hello World
